# Generated by Django 5.1.1 on 2024-09-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_profile_memeber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='memeber',
            new_name='member',
        ),
    ]
