# Generated by Django 5.1.1 on 2024-09-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_memeber_profile_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='member',
            new_name='user',
        ),
    ]
